# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci 
    - name: Build Application
      run: npm run build --if-present
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with: 
        name: musa-build
        path: build/
  release:
    name: Release Plugin
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with: 
        name: musa-build
    - name: Archive
      uses: thedoctor0/zip-release@main
      with: 
        filename: musa-apollonides.zip
    - name: Install jq tool
      run: |
        sudo apt-get update
        sudo apt-get install jq
    - name: Find Version Number
      run: echo "MUSAVERSION=`cat manifest.json |jq -r .version`" >> $GITHUB_ENV
    - name: Check Var
      run: echo "${{ env.MUSAVERSION }}"
    - name: Create Release
      uses: ncipollo/release-action@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag: v${{ env.MUSAVERSION }}
        artifacts: musa-apollonides.zip
        token: ${{ env.GITHUB_TOKEN }}
